### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by wedot** [la-haute-societe/craft-tarteaucitron#9]
Hello

I'm trying to unload all styles for tarteaucitron using the "Use external CSS" option, but the file will still be loaded.

And i'd like to inject the scrips with a javascript into the body end. 
Are you planning to build the plugin in a way so that users can use your user interface in the Craft CMS, but get more control over the output in the frontend?

<img width="902" alt="Bildschirmfoto 2021-01-12 um 12 28 43" src="https://user-images.githubusercontent.com/22647218/104309468-7fdd3180-54d2-11eb-8093-6ff98cbe6337.png">
<img width="389" alt="Bildschirmfoto 2021-01-12 um 12 32 49" src="https://user-images.githubusercontent.com/22647218/104309471-81a6f500-54d2-11eb-9579-01e9eb54cacd.png">

**Comment by nstcactus** [comment]
Hi, 

I'll work on a fix for the **Use external CSS** setting that is ignored. 

Regarding you other question, I'm not sure I understand what you want to achieve. Can you explain in details the output you expect?

**Comment by wedot** [comment]
Thank you, that will be great.

I'd like to do a few things:

1. Inject the Script via a JavaScript into the body, to get a better performance by loading the site and get a better page speed. Something like: http://www.javascriptkit.com/javatutors/loadjavascriptcss.shtml
2. With the script I could load the script dynamically, as well as the stylesheet. So if someone doesn't use JavaScript the style won't be loaded at all and the other way I don't get a render blocking on the page.
3. use my own css to match the brand design

I'm not very into Plugin Dev witn Craft CMS. Maybe it could be a good way to do something like:
{{ craft.tarteaucitron.initStyleSheet }}
{{ craft.tarteaucitron.initJavaScript }}
{{ craft.tarteaucitron. initScriptConfig }}

**Comment by wedot** [comment]
It's me again. Could you look into that issue? Because I'm not into Craft plugin dev. I can't offer you my support.
That do you think you will release a new Version of your Plugin? Or should I build something with tarteaucitron myself without a plugin?

**Comment by nstcactus** [comment]
Sorry for the delay, we've been busy!

I just pushed a new version that fixes the ignored `useExternalCss` setting bug and adds the following methods to give you more control on the output:
- `{{ craft.tarteaucitron.javascriptImportTag }}`
- `{{ craft.tarteaucitron. javascriptConfigTag }}`
- `{{ craft.tarteaucitron.stylesheetTag }}`

Hope this works for you. Feel free to re-open if it doesn't.

**Comment by nstcactus** [comment]
I just noticed I forgot to deploy to the Craft plugin store. It's now fixed: https://plugins.craftcms.com/tarteaucitron

**Comment by wedot** [comment]
Thanks, I tested it yesterday by installing it by hand. I will give you some feedback very soon. Thanks for your work.
